# Controller generated by Typus, use it to extend admin functionality.
class Admin::TaggedLinksController < Admin::ResourcesController
  def fetch_links
    TaggedLink.fetch_links_for_all_tags
    redirect_to :action => :index
  end
end
