# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Configuration:
  fields:
    default: name, value, type
    form: name, value, type
  order_by: 
  relationships: 
  filters: 
  search: name
  application: urlagg

Link:
  fields:
    default: url, title, bookmarks, last_seen_in_feed
    form: url, title, summary, bookmarks, last_seen_in_feed, source_tags
  order_by: 
  relationships: tagged_links, tags
  filters: 
  search: title
  application: urlagg

SuperUser:
  fields:
    default: login, email, login_count, last_request_at, last_login_at, current_login_at, last_login_ip, current_login_ip
    form: login, email, login_count, last_request_at, last_login_at, current_login_at, last_login_ip, current_login_ip
  order_by: 
  relationships: 
  filters: 
  search: 
  application: urlagg

Tag:
  fields:
    default: name, taggings_count
    form: name, taggings_count
  order_by: 
  relationships: links, tagged_links, taggings
  filters: 
  search: name
  application: urlagg

TaggedLink:
  fields:
    default: tag_id, link_id, link, tag
    form: tag_id, link_id, link, tag
  order_by: 
  relationships: link, tag
  filters: 
  search: 
  application: urlagg

Tagging:
  fields:
    default: user_id, tag_id, position, last_seen_at, user, tag
    form: user_id, tag_id, last_seen_at, user, tag
  order_by: position
  relationships: tag, user
  filters: 
  search: 
  application: urlagg

User:
  fields:
    default: login, email, login_count, last_request_at, last_login_at, current_login_at, last_login_ip, current_login_ip, last_viewed_tags_index_at
    form: login, email, login_count, last_request_at, last_login_at, current_login_at, last_login_ip, current_login_ip, last_viewed_tags_index_at
  order_by: 
  relationships: taggings, tags
  filters: 
  search: 
  application: urlagg

