set :application, "urlagg"
set :repository, "git@github.com:jschoolcraft/URLAgg.git"
set :user, "jeff"
set :use_sudo, true
set :deploy_via, :fast_remote_cache
 
set :keep_releases, 6
set :config_files, %w(database.yml newrelic.yml initializers/hoptoad.rb)

after "deploy:update", "deploy:cleanup"

namespace :sass do
  desc 'Updates the stylesheets generated by Sass'
  task :update, :roles => :app do
    invoke_command "cd #{latest_release}; RAILS_ENV=#{rails_env} rake sass:update"
  end

  # Generate all the stylesheets manually (from their Sass templates) before each restart.
  before 'deploy:restart', 'sass:update'
end